version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - '3001:3001'
    environment:
      VITE_API_URL: http://localhost:3000/api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production # test for testing
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development # test for testing
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/tocos-trading-system
      TEST_MONGODB_URI: mongodb://localhost:27017/test

  mongo:
    image: mongo:4.2.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
